# -*- coding: utf-8 -*-
"""equation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CBFeefcqF4KgUDPbg8UBt3xTmXpKf5vd
"""

n=int(input("Enter the number:"))
answer=n+(n**2)+(n**3)
print("The answer is:",answer)